[package]
name = "wiki-graph"
version = "0.1.0"
edition = "2021"



[lib]
crate-type = ["cdylib"]

[dependencies]
petgraph = "0.6.4"
serde = { version = "1.0.198" , features = ["derive"]}
serde_json = "1.0"
wasm-bindgen = "0.2.92"
